import ButtonLogin from '@/common/ButtonLogin'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>AIS-DX Platform</title>
       <ButtonLogin/>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
            </Head>
      <main>
        AIS-DX
      </main>
    </>
  )
}
